import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import { eq } from 'drizzle-orm';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { buildApp } from '../../src/server/app.js';
import { closeDatabase, getDb } from '../../src/database/client.js';
import { closeRedis } from '../../src/redis/client.js';
import { closeQueues, QUEUE_NAMES, getQueue } from '../../src/queue/queues.js';
import { seed } from '../../src/database/seed.js';
import {
  downloadJobs,
  files,
  mediaFormats,
  mediaMetadata,
} from '../../src/database/schema/index.js';
import { createDownloadWorker } from '../../src/workers/download-worker.js';
import { runnerControls } from '../../src/workers/runner.js';
import type { AppInstance } from '../../src/types/app.js';
import { infraAvailable, inCi } from '../helpers/infra.js';

const execFileAsync = promisify(execFile);

const infraUp = await infraAvailable();

/** The E2E suite needs a real ffmpeg to mint the fixture media file. */
async function ffmpegAvailable(): Promise<boolean> {
  try {
    await execFileAsync('ffmpeg', ['-version'], { timeout: 5_000 });
    return true;
  } catch {
    return false;
  }
}
const hasFfmpeg = await ffmpegAvailable();
const describeRun = describe.runIf((infraUp && hasFfmpeg) || inCi);

const ANON_KEY = 'pipeline-anon-key-1';

interface JobView {
  id: string;
  status: string;
  progress: string | number;
  requestedFormat: string | null;
  errorCode: string | null;
}

interface AnalyzeView {
  url: string;
  title: string | null;
  durationSec: number | null;
  formats: Array<{ key: string; container: string; isDefault: boolean }>;
}

describeRun('media engine pipeline (integration)', () => {
  let app: AppInstance;
  let worker: ReturnType<typeof createDownloadWorker>;
  let server: http.Server;
  let baseUrl: string;
  let fixtureDir: string;
  let fixtureBytes: Buffer;
  let fixtureSha: string;
  const originalMode = runnerControls.mode;

  beforeAll(async () => {
    await seed();

    // 1×1-scale real MP4 generated by ffmpeg - yt-dlp and ffprobe both see
    // a genuine media file, so every pipeline guard runs for real.
    fixtureDir = await mkdtemp(join(tmpdir(), 'fd-fixture-'));
    const fixturePath = join(fixtureDir, 'fixture.mp4');
    await execFileAsync(
      'ffmpeg',
      [
        '-y',
        '-f',
        'lavfi',
        '-i',
        'testsrc=duration=1:size=64x64:rate=10',
        '-pix_fmt',
        'yuv420p',
        fixturePath,
      ],
      { timeout: 30_000 },
    );
    fixtureBytes = await readFile(fixturePath);
    const { createHash } = await import('node:crypto');
    fixtureSha = createHash('sha256').update(fixtureBytes).digest('hex');

    server = http.createServer((req, res) => {
      if (req.url?.startsWith('/video.mp4')) {
        res.writeHead(200, {
          'content-type': 'video/mp4',
          'content-length': String(fixtureBytes.length),
        });
        res.end(fixtureBytes);
        return;
      }
      res.writeHead(404, { 'content-type': 'text/plain' });
      res.end('not found');
    });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    baseUrl = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;

    app = await buildApp({ rateLimit: false });
    await app.ready();

    const queue = getQueue(QUEUE_NAMES.downloads);
    await queue.drain(true).catch(() => undefined);
    await queue.clean(0, 1000, 'failed').catch(() => undefined);

    runnerControls.mode = 'pipeline';
    worker = createDownloadWorker(1);
    await worker.waitUntilReady();
  }, 60_000);

  afterAll(async () => {
    runnerControls.mode = originalMode;
    await worker?.close();
    await app?.close();
    await closeQueues();
    await closeDatabase();
    await closeRedis();
    // beforeAll can die before the fixture server exists (e.g. ffmpeg
    // missing) - don't let teardown mask the real error with a TypeError.
    if (server) {
      await new Promise<void>((resolve) => server.close(() => resolve()));
    }
    await rm(fixtureDir, { recursive: true, force: true }).catch(() => undefined);
  });

  async function createJob(body: Record<string, unknown>): Promise<JobView> {
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/downloads',
      headers: { 'x-anon-key': ANON_KEY },
      payload: body,
    });
    expect(res.statusCode).toBe(201);
    return res.json() as JobView;
  }

  async function readJob(id: string): Promise<JobView> {
    const res = await app.inject({
      method: 'GET',
      url: `/api/v1/downloads/${id}`,
      headers: { 'x-anon-key': ANON_KEY },
    });
    expect(res.statusCode).toBe(200);
    return res.json() as JobView;
  }

  async function waitFor(id: string, accepts: string[], timeoutMs: number): Promise<JobView> {
    const deadline = Date.now() + timeoutMs;
    let last: JobView | undefined;
    while (Date.now() < deadline) {
      last = await readJob(id);
      if (accepts.includes(last.status)) return last;
      await new Promise((resolve) => setTimeout(resolve, 300));
    }
    throw new Error(`job ${id} never reached ${accepts.join('|')} (last: ${last?.status})`);
  }

  it('analyzes a URL and serves the format list (cached)', async () => {
    const payload = { url: `${baseUrl}/video.mp4?token=secret-should-not-leak` };
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/downloads/analyze',
      headers: { 'x-anon-key': ANON_KEY },
      payload,
    });
    expect(res.statusCode).toBe(200);
    const body = res.json() as AnalyzeView;
    expect(body.url).not.toContain('secret-should-not-leak'); // query stripped
    expect(body.formats.length).toBeGreaterThanOrEqual(1);
    expect(body.formats.some((f) => f.container === 'mp4')).toBe(true);

    // Second call is served from the Redis cache - identical payload.
    const cached = await app.inject({
      method: 'POST',
      url: '/api/v1/downloads/analyze',
      headers: { 'x-anon-key': ANON_KEY },
      payload,
    });
    expect(cached.statusCode).toBe(200);
    expect((cached.json() as AnalyzeView).title).toBe(body.title);
  }, 60_000);

  it('runs the full pipeline: analyze → download → remux → store → result bytes', async () => {
    const created = await createJob({
      url: `${baseUrl}/video.mp4`,
      format: 'mp4',
      container: 'mp4',
    });
    const done = await waitFor(created.id, ['completed', 'failed', 'dead_letter'], 60_000);
    expect(done.status).toBe('completed');
    expect(done.progress).toBe(100);

    // Structured analysis landed in PG...
    const meta = await getDb()
      .select()
      .from(mediaMetadata)
      .where(eq(mediaMetadata.jobId, created.id));
    expect(meta).toHaveLength(1);
    expect(meta[0]!.fetchedAt).toBeTruthy();
    const formats = await getDb()
      .select()
      .from(mediaFormats)
      .where(eq(mediaFormats.jobId, created.id));
    expect(formats.length).toBeGreaterThanOrEqual(1);

    // ...and the file row records the real stored object.
    const rows = await getDb().select().from(files).where(eq(files.jobId, created.id));
    expect(rows).toHaveLength(1);
    expect(rows[0]!.objectKey).toContain(created.id);
    expect(rows[0]!.container).toBe('mp4');
    expect(rows[0]!.checksumSha256).toBe(fixtureSha);
    expect(rows[0]!.sizeBytes).toBe(fixtureBytes.length);

    // Signed result URL streams identical bytes through the local driver.
    const res = await app.inject({
      method: 'GET',
      url: `/api/v1/downloads/${created.id}/result`,
      headers: { 'x-anon-key': ANON_KEY },
    });
    expect(res.statusCode).toBe(200);
    const result = res.json() as { url: string; downloadUrl: string; sizeBytes: number | null };
    const signed = new URL(result.url);
    const dl = await app.inject({
      method: 'GET',
      url: `${signed.pathname}${signed.search}`,
    });
    expect(dl.statusCode).toBe(200);
    expect(dl.rawPayload.length).toBe(fixtureBytes.length);
    expect(Buffer.from(dl.rawPayload).equals(fixtureBytes)).toBe(true);
    // Inline variant: playable as a cross-origin <video> source.
    expect(dl.headers['content-disposition']).toContain('inline;');
    expect(dl.headers['cross-origin-resource-policy']).toBe('cross-origin');

    // Download variant: forces a save-to-device.
    const down = new URL(result.downloadUrl);
    expect(down.searchParams.get('dl')).toBe('1');
    const dlRes = await app.inject({
      method: 'GET',
      url: `${down.pathname}${down.search}`,
    });
    expect(dlRes.statusCode).toBe(200);
    expect(dlRes.headers['content-disposition']).toContain('attachment;');

    // The raw URL is never echoed back to the client.
    expect(JSON.stringify(result)).not.toContain('127.0.0.1');
  }, 90_000);

  it('parks at ready without a format, then completes after /start', async () => {
    const created = await createJob({ url: `${baseUrl}/video.mp4` });
    const parked = await waitFor(created.id, ['ready', 'failed', 'dead_letter'], 60_000);
    expect(parked.status).toBe('ready');

    // The DB row knows the format the user will pick.
    const row = (
      await getDb()
        .select({ id: downloadJobs.id, analyzedAt: downloadJobs.analyzedAt })
        .from(downloadJobs)
        .where(eq(downloadJobs.id, created.id))
    )[0];
    expect(row?.analyzedAt).toBeTruthy();

    const startRes = await app.inject({
      method: 'POST',
      url: `/api/v1/downloads/${created.id}/start`,
      headers: { 'x-anon-key': ANON_KEY },
      payload: { format: 'mp4', container: 'mp4' },
    });
    expect(startRes.statusCode).toBe(200);
    const started = startRes.json() as JobView;
    expect(started.status).toBe('processing');

    const done = await waitFor(created.id, ['completed', 'failed', 'dead_letter'], 60_000);
    expect(done.status).toBe('completed');

    const result = await app.inject({
      method: 'GET',
      url: `/api/v1/downloads/${created.id}/result`,
      headers: { 'x-anon-key': ANON_KEY },
    });
    expect(result.statusCode).toBe(200);
    expect((result.json() as { url: string }).url).toContain('files/');
  }, 90_000);

  it('rejects starting a job that is not ready and reading a result early', async () => {
    const created = await createJob({ url: `${baseUrl}/video.mp4`, format: 'mp4' });
    const done = await waitFor(created.id, ['completed', 'failed', 'dead_letter'], 60_000);
    expect(done.status).toBe('completed');

    const startAgain = await app.inject({
      method: 'POST',
      url: `/api/v1/downloads/${created.id}/start`,
      headers: { 'x-anon-key': ANON_KEY },
      payload: { format: 'mp4' },
    });
    expect(startAgain.statusCode).toBe(409);

    // Result of a fresh non-completed job is 409 too.
    const fresh = await createJob({ url: `${baseUrl}/video.mp4`, format: 'mp4' });
    const early = await app.inject({
      method: 'GET',
      url: `/api/v1/downloads/${fresh.id}/result`,
      headers: { 'x-anon-key': ANON_KEY },
    });
    expect([409]).toContain(early.statusCode);

    await waitFor(fresh.id, ['completed', 'failed', 'dead_letter'], 60_000);
  }, 90_000);

  it('validates format and container keys before anything is queued', async () => {
    const bad = await app.inject({
      method: 'POST',
      url: '/api/v1/downloads',
      headers: { 'x-anon-key': ANON_KEY },
      payload: { url: `${baseUrl}/video.mp4`, container: 'sh;id' },
    });
    expect(bad.statusCode).toBe(400);
  });

  it('serves the public catalog', async () => {
    const sources = await app.inject({ method: 'GET', url: '/api/v1/sources' });
    expect(sources.statusCode).toBe(200);
    const srcBody = sources.json() as { data: Array<{ slug: string; mode: string }> };
    expect(srcBody.data.some((s) => s.slug === 'generic' && s.mode === 'active')).toBe(true);

    const formats = await app.inject({ method: 'GET', url: '/api/v1/formats' });
    expect(formats.statusCode).toBe(200);
    const fmtBody = formats.json() as { data: Array<{ key: string }> };
    expect(fmtBody.data.map((f) => f.key)).toContain('mp4');

    const cfg = await app.inject({ method: 'GET', url: '/api/v1/config/public' });
    expect(cfg.statusCode).toBe(200);
    const cfgBody = cfg.json() as {
      limits: { maxFileSizeMb: number };
      plans: unknown[];
      turnstile: { enabled: boolean };
    };
    expect(cfgBody.limits.maxFileSizeMb).toBeGreaterThan(0);
    expect(cfgBody.plans.length).toBeGreaterThanOrEqual(3);
    expect(typeof cfgBody.turnstile.enabled).toBe('boolean');
  }, 30_000);
});
